# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'AzureConnection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo 'Install Azure DevOps Extension on the agent'
      az extension add --name azure-devops
      
      echo 'Verify Extension installation'
      az extension list
      
      echo 'Configure project defaults'
      az devops configure --defaults organization='$(System.TeamFoundationCollectionUri)' project='$(System.TeamProject)'
      
      echo 'List configuration - Azure DevOps Extension'
      az devops configure --list
      
      echo 'Installation completed'
  displayName: 'Azure DevOps Extension installation'

- task: pipelineextensiontest@0
  inputs:
    samplestring: 'Human'
    timeout: '600'
    listofchildpipelines: 'child1 123, child2 456, child3 789'
